### ISSUE TITLE
Streaming with requests before login is finished

### ISSUE THREAD

**Issue by pmettler** [areed1192/td-ameritrade-python-api#102]
Hello, I know that this topic was discussed before but the problem still exists in my case:

I use the scripts exactly as uploaded here (0.3.0) and explained in the videos (just fantastic these explanations, thx for that).

My script:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/70354459/92411054-540d0200-f114-11ea-85a1-9fab244a274c.png">

And the failure message:

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/70354459/92411043-45bee600-f114-11ea-9d9e-cfec494b4cfb.png">

Sometimes it works, sometimes not. I see that others are talking about a fixed bug. But not in my case (MAC user)

Is there any explanation for that? Or something I need to change? Thanks in advance for any help

**Comment by seismars** [comment]
Same issue happened to me on Linux.
I was able to get around the issue following the change suggested by pull request #87.

**Comment by pmettler** [comment]
I also tried to go that way

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/70354459/92417838-61d18000-f132-11ea-86d3-a2cff8443efb.png">

Same issue...

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/70354459/92417848-70b83280-f132-11ea-87bc-3262aef1219a.png">

Or did I overlook something? I mean, I still work with the json file as my credentials but the rest is the same.

**Comment by pmettler** [comment]
This morning I switched over to Windows/ MS.

Everything works perfectly fine. But unfortunately I cannot confirm that the fix suggested by pull request #87 is working on a MAC (Catalina, 10.15.6)

So of there is anybody who has another idea please let me know. I'd rather to continue my work on my MAC. Thanks in advance

**Comment by joecat808** [comment]
Ok I may have found a very crude workaround. I modified the stream.py file inside the td folder by adding 2 additional lines to the "async def _send_message(self, message: str)" function:

`async def _send_message(self, message: str):
        """Sends a message to webSocket server

        Arguments:
        ----
        message {str} -- The JSON string with the
            data streaming service subscription.
        """        
        if 'LOGIN' not in message:
            await asyncio.sleep(1)
        await self.connection.send(message)`

Since message is a string, the if statement checks if "LOGIN" exists in it. If it does, it proceeds as normal. If it doesn't (ie it's a data request message), it sleeps for 1 second. I'm a total python newbie and there is probably a much smarter way to do this, but it's working for me now.

**Comment by joecat808** [comment]
Ok I may have found a very crude workaround. I modified the stream.py file inside the td folder by adding 2 additional lines to the "async def _send_message(self, message: str)" function:

```
async def _send_message(self, message: str):
"""Sends a message to webSocket server

    Arguments:
    ----
    message {str} -- The JSON string with the
        data streaming service subscription.
    """        
    if 'LOGIN' not in message:
        await asyncio.sleep(1)
    await self.connection.send(message)
```

Since message is a string, the if statement checks if "LOGIN" exists in it. If it does, it proceeds as normal. If it doesn't (ie it's a data request message), it sleeps for 1 second. I'm a total python newbie and there is probably a much smarter way to do this, but it's working for me now.

**Comment by seismars** [comment]
This workaround works for me as well. Thanks. I wish there is an official fix in the original package later.

**Comment by pmettler** [comment]
Thanks a lot for the support. 

Right now I stay with my Windows Account as my Token is assigned to that. That means I cannot check that solution. 

The reason is, that TD blocked another creation of a new token with the message: Third Party is trying to access... blocked. 

Question:
Does it make a difference if I put my APP in TDA Developer to 'http' or 'https'? With my MAC it was easy to create a local Webserver with 'https' but I don't get it accomplished for Windows. I assume that this is the reason. Is there somebody with ideas?

**Comment by areed1192** [comment]
Just wanted to let everyone know that this fix will be integrated into the next release. @joecat808, thanks for offering the solution.
