### ISSUE TITLE
Problem with get_price_history client.py

### ISSUE THREAD

**Issue by AMoir117** [areed1192/td-ameritrade-python-api#103]
So, on line **742 in client.py** you have:

```python
if (start_date and end_date and period):
            raise ValueError('Cannot have Period with start date and end date')
```

This code doesn't make sense because you can send a valid request with a; period, `start_date`, and `end_date` (i.e.):

```python
TDSession.get_price_history(
    symbol=self.symbol,
    start_date=int(time()*1000),
    end_date=int(time()*1000),
    extended_hours=False,
    period_type='day',
    period=10,
    frequency=1,
    frequency_type='minute'
)
```

Note: code above only works during market hours otherwise it is a bad request

**Comment by areed1192** [comment]
Regarding this, are you saying you were able to run the code even if you pass all three arguments, or are you saying that the API wouldn't return an error if all three were sent along?

Originally, this constraint was added because the Documentation said you couldn't combine all three but it's possible it could've changed.
