### ISSUE TITLE
Account number and password

### ISSUE THREAD

**Issue by dodoei** [areed1192/td-ameritrade-python-api#21]
Hi, just wondering what are account number and password used for? Didn't see anywhere in the code that needs it? So can I not put those in?

**Comment by RossGlengarry** [comment]
They're necessary for gaining access to anything useful.  There is some
basic info available to query without it I believe, though.  Refer to the
official API documentation on TD for exact details.

Cheers

**Comment by reikred** [comment]
My experience is that you can run TDSession.get_accounts() and gett all balances etc WITHOUT a valid account_number and account_password , as long as you have the  consumer_id (aka. consumer_key I think).

If they are not used, these variables probably should be removed from the code and the examples. They just lead to people having script laying around with plaintext secrets in them

**Comment by areed1192** [comment]
I just wanted to chime in and let you know that going forward; I will be removing the account password from the client object. I agree; if it's not being used anywhere, there is no sense to ask for it. For the account number, I might keep that out, just because any of the endpoints that require it; I'm already asking for it.

Ideally, the only thing that the client needs from the user is the redirect URI and the `client_id`. Also, the new `credentials_path` argument will be used to load an existing JSON file used for authentication.
